baseURL = "https://l9o.dev/"
languageCode = "en-us"
title = "l9o.dev"
theme = "hello-friend"
copyright = " "

[params]
  rssFullText = true

[languages]
  [languages.en]
    title = "l9o.dev"
    subtitle = "Luiz Ribeiro's blog"

    [languages.en.params.logo]
      logoText = "l9o.dev"
      logoHomeLink = "/"
